dist: trusty
sudo: required
addons:
  sonarcloud:
    organization: channelape-github
    token:
      secure: KP2Ui6oyfp1+LiYRaxQRhGlpca5J7zeDf2UesjOyAUkkOg+qlyGc5O7zwnx1d3I4bLz3rzhPmVXbLHAfsI5r3ODtavXlge4ziqyfD9oLmNizXPXjX5+0wyMb8GHnIf+vftaMHMKlJTeoP30g842Ec6n3H2PFW/f62VST0Q01ZXhqWIw150NkG6fwcUnhQ5gwAMWcsIw/lwcvRFx4zkQPYM24/o8uEgIgIZI//zZXSljRrSBmg0kWXnqDfFpfTvbslTjJSJ4K0P1877GPWG8ExIHZiOYq8Fvg48/W6ANonMGYpDfsaDIZ74QAbHJi+Mwj/OFUdmhXAgBVx1D+zWiejHxicyY6Xa8OlP48vDXItL8jQYzoVRu9rlFcm28PTa/mUJhBtroXsU7yig4fc9spTxQJOaV5watmQs8WRvEPSYlEXgY7Ui8aA40/9lISC3ELJAfTlm3FZRBQ2rth0Q/cfJfhq//JUE1/xQrtxyesTNhEzzybteZLKEnTPfHBKNs24PTF5PZbXF9rAGL8hefczTXm2lrBg3zJXZui37q7IrdX/Ta/Kl//NH4vK7LqgQ7b+PDH+HRJQb+ZO+2ZBMY8PqrFMa/kgnWsaLzX+O2o2unuQwRCCN4lb0ea3eureJM98lC1IpU7MBRtHeQKkL1Ohup8vE3M1f0y+cJqa9D6B7I=
language: node_js
node_js:
- 8.10.0
jdk:
- oraclejdk8
install:
- npm install
script:
- npm test
after_success:
- bash .travis/overwrite-sonar-project-version.sh
- sonar-scanner
cache:
  directories:
  - node_modules
  - "$HOME/.sonar/cache"
deploy:
  provider: npm
  skip_cleanup: true
  email:
    - "$NPM_EMAIL"
  api_key:
    - "$NPM_TOKEN"
  on:
    tags: true
